server:
  port: 1018

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      registry-fetch-interval-seconds: 3
  instance:
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12



spring:
  application:
    name: AppleStore-Order-Service
#  zipkin:
#    base-url: http://112.124.18.163:9411/
  sleuth:
    sampler:
      probability: 1
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz9oa6p4h17oz46u1co.mysql.rds.aliyuncs.com/applestore_dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=CTT
    username: macross
    password: 19981015@zJh
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080

AppleStore-Commodity-Service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 4000

  hystrix:
    enabled: true
  sentinel:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: "*"

#MyBatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.macross.AppleStore_Common_Config.model
